(in-package :paquete-unificacion)

(define-test test-atomo
  (format t "    (atomo '1) -> ")
  (assert-equal T (atomo '1))
  (format t "    (atomo 'A) -> ")
  (assert-equal T (atomo 'A))
  (format t "    (atomo '(A B)) -> ")
  (assert-equal NIL (atomo '(A B)))
  (format t "    (atomo '(? X)) -> ")
  (assert-equal T (atomo '(? X)))
  (format t "    (atomo '(? X Y)) -> ")
  (assert-equal NIL (atomo '(? X Y)))
)

(define-test test-es-variable
  (format t "    (es-variable '(? X)) -> ")
  (assert-equal T (es-variable '(? X)))
  (format t "    (es-variable '(? Y)) -> ")
  (assert-equal T (es-variable '(? Y)))
  (format t "    (es-variable 'X) -> ")
  (assert-equal NIL (es-variable 'X))
  (format t "    (es-variable '1) -> ")
  (assert-equal NIL (es-variable '1))
  (format t "    (es-variable '(? X Y)) -> ")
  (assert-equal NIL (es-variable '(? X Y)))
  (format t "    (es-variable '(1 2 3)) -> ")
  (assert-equal NIL (es-variable '(1 2 3)))
)

(define-test test-aparece-en
  (format t "    (aparece-en 'A '(A B C)) -> ")
  (assert-equal T (aparece-en 'A '(A B C)))
  (format t "    (aparece-en 'B '(A B C)) -> ")
  (assert-equal T (aparece-en 'B '(A B C)))
  (format t "    (aparece-en 'C '(A B C)) -> ")
  (assert-equal T (aparece-en 'C '(A B C)))
  (format t "    (aparece-en '(? X) '(A (? X) C)) -> ")
  (assert-equal T (aparece-en '(? X) '(A (? X) C)))
  (format t "    (aparece-en '(? X) '(A ((? X) C))) -> ")
  (assert-equal T (aparece-en '(? X) '(A ((? X) C))))
  (format t "    (aparece-en 'A '(B C D)) -> ")
  (assert-equal NIL (aparece-en 'A '(B C D)))
  (format t "    (aparece-en 'A '(B (C D))) -> ")
  (assert-equal NIL (aparece-en 'A '(B (C D))))
  (format t "    (aparece-en '(? X) '(B (? Y) D)) -> ")
  (assert-equal NIL (aparece-en '(? X) '(B (? Y) D)))
  (format t "    (aparece-en '(? X) '((B (? Y)) D)) -> ")
  (assert-equal NIL (aparece-en '(? X) '((B (? Y)) D)))
)

(define-test test-aplicar
  (format t "    (aplicar 'NADA '(f (? x))) -> ")
  (assert-equal '(f (? x)) (aplicar 'NADA '(f (? x))))
  (format t "    (aplicar '( (A (? x)) ) '()) -> ")
  (assert-equal '() (aplicar '( (A (? x)) ) '()))
  (format t "    (aplicar '( (A (? x)) ) '(? x)) -> ")
  (assert-equal 'A (aplicar '( (A (? x)) ) '(? x)))
  (format t "    (aplicar '( (A (? x)) (B (? y)) ) '(? y)) -> ")
  (assert-equal 'B (aplicar '( (A (? x)) (B (? y)) ) '(? y)))
  (format t "    (aplicar '( (A (? x)) ) '((? x))) -> ")
  (assert-equal '(A) (aplicar '( (A (? x)) ) '((? x))))
  (format t "    (aplicar '( (A (? x)) ) '(f (? y) (? x))) -> ")
  (assert-equal '(f (? y) A) (aplicar '( (A (? x)) ) '(f (? y) (? x))))
  (format t "    (aplicar '( (A (? x)) ) '(f (g (? x)))) -> ")
  (assert-equal '(f (g A)) (aplicar '( (A (? x)) ) '(f (g (? x)))))
  (format t "    (aplicar '( (A (? x)) (B (? y)) ) '(f (? x) (? y))) -> ")
  (assert-equal '(f A B) (aplicar '( (A (? x)) (B (? y)) ) '(f (? x) (? y))))
  (format t "    (aplicar '( (A (? x)) (B (? y)) ) '(f A (g (h (? x))) (g (h (? y))))) -> ")
  (assert-equal '(f A (g (h A)) (g (h B))) (aplicar '( (A (? x)) (B (? y)) ) '(f A (g (h (? x))) (g (h (? y))))))
  (format t "    (aplicar '( (A (? x)) (B (? y)) ) '(f A (g (h (? x))) (g (h (? y))))) -> ")
  (assert-equal '(f A B (g C)) (aplicar '( (A (? x)) (B (? y)) (C (? w)) ) '(f (? x) (? y) (g (? w)))))
)

(define-test test-componer
  (format t "    (componer 'NADA '( (A (? x)) )) -> ")
  (assert-equal '( (A (? x)) ) (componer 'NADA '( (A (? x)) )))
  (format t "    (componer  '( (A (? x)) ) 'NADA) -> ")
  (assert-equal '( (A (? x)) ) (componer  '( (A (? x)) ) 'NADA))
  (format t "    (componer 'NADA '( (A (? x)) (B (? y)) )) -> ")
  (assert-equal '( (A (? x)) (B (? y)) ) (componer 'NADA '( (A (? x)) (B (? y)) )))
  (format t "    (componer '( (A (? x)) (B (? y)) ) 'NADA) -> ")
  (assert-equal '( (A (? x)) (B (? y)) ) (componer '( (A (? x)) (B (? y)) ) 'NADA))
  (format t "    (componer '( ((? x) (? z)) ) '( (A (? x)) )) -> ")
  (assert-equal '( (A (? z)) (A (? x)) ) (componer '( ((? x) (? z)) ) '( (A (? x)) )))
  (format t "    (componer '( ((? x) (? z)) ) '( (A (? x)) (B (? y)) )) -> ")
  (assert-equal '( (A (? z)) (A (? x)) (B (? y)) ) (componer '( ((? x) (? z)) ) '( (A (? x)) (B (? y)) )))
  (format t "    (componer '( ((? x) (? z)) ((? y) (? w)) ) '( (A (? x)) (B (? y)) )) -> ")
  (assert-equal '( (A (? z)) (B (? w)) (A (? x)) (B (? y)) ) (componer '( ((? x) (? z)) ((? y) (? w)) ) '( (A (? x)) (B (? y)) )))
  (format t "    (componer '( ((? x) (? z)) ((? y) (? w)) (C (? k)) ) '( (A (? x)) (B (? y)) )) -> ")
  (assert-equal '( (A (? z)) (B (? w)) (C (? k)) (A (? x)) (B (? y)) ) (componer '( ((? x) (? z)) ((? y) (? w)) (C (? k)) ) '( (A (? x)) (B (? y)) )))
  (format t "    (componer '( ((g (? x) (? y)) (? z)) ) '( (A (? x)) (B (? y)) (C (? w)) (D (? z)) )) -> ")
  (assert-equal '( ((g A B) (? z)) (A (? x)) (B (? y)) (C (? w)) ) (componer '( ((g (? x) (? y)) (? z)) ) '( (A (? x)) (B (? y)) (C (? w)) (D (? z)) )))
  (format t "    (componer '( ((g (? x) (? y)) (? w)) ) '( (A (? x)) (B (? y)) (C (? w)) (D (? z)) )) -> ")
  (assert-equal '( ((g A B) (? w)) (A (? x)) (B (? y)) (D (? z)) ) (componer '( ((g (? x) (? y)) (? w)) ) '( (A (? x)) (B (? y)) (C (? w)) (D (? z)) )))
  (format t "    (componer '( ((g (? w) (? y)) (? x)) ) '( (A (? x)) (B (? y)) (C (? w)) (D (? z)) )) -> ")
  (assert-equal '( ((g C B) (? x)) (B (? y)) (C (? w)) (D (? z)) ) (componer '( ((g (? w) (? y)) (? x)) ) '( (A (? x)) (B (? y)) (C (? w)) (D (? z)) )))
)

(define-test test-unificar
  (format t "    Pruebas de la parte de hayAtomo --> 2 elementos iguales~%")
  (format t "        (unificar 'f 'f) -> ")
  (assert-equal 'NADA (unificar 'f 'f))
  (format t "        (unificar '(? X) '(? X)) -> ")
  (assert-equal 'NADA (unificar '(? X) '(? X)))
  (format t "    Pruebas de la parte de hayAtomo --> Una sustitución sencilla~%")
  (format t "        (unificar 'A '(? X)) -> ")
  (assert-equal '( (A (? X)) ) (unificar 'A '(? X)))
  (format t "        (unificar '(? X) 'A) -> ")
  (assert-equal '( (A (? X)) ) (unificar '(? X) 'A))
  (format t "    Pruebas de la parte de hayAtomo --> Una sustitución más compleja~%")
  (format t "        (unificar '(? X) '(F A)) -> ")
  (assert-equal '( ((F A) (? X)) ) (unificar '(? X) '(F A)))
  (format t "        (unificar '(F A) '(? Y)) -> ")
  (assert-equal '( ((F A) (? Y)) ) (unificar '(F A) '(? Y)))
  (format t "    Pruebas de la parte de hayAtomo --> 2 elementos distintos~%")
  (format t "        (unificar 'A 'B) -> ")
  (assert-equal 'FALLO (unificar 'A 'B))
  (format t "        (unificar 'A '(F A)) -> ")
  (assert-equal 'FALLO (unificar 'A '(F A)))
  (format t "    Pruebas de la parte de hayAtomo --> Tras la implementación de aparece-en~%")
  (format t "        (unificar '(? X) '(F (? X))) -> ")
  (assert-equal 'FALLO (unificar '(? X) '(F (? X))))
  (format t "        (unificar '(F (? X)) '(? X)) -> ")
  (assert-equal 'FALLO (unificar '(F (? X)) '(? X)))
  (format t "    Pruebas de la parte de recursividad~%")
  (format t "        (unificar '(f (? X)) '(f A)) -> ")
  (assert-equal '( (A (? X)) ) (unificar '(f (? X)) '(f A)))
  (format t "        (unificar '(f A) '(f (? X))) -> ")
  (assert-equal '( (A (? X)) ) (unificar '(f A) '(f (? X))))
  (format t "        (unificar '(f A) '(f B)) -> ")
  (assert-equal 'FALLO (unificar '(f A) '(f B)))
  (format t "        (unificar '(f (? X) (? Y)) '(f A B)) -> ")
  (assert-equal '( (A (? X)) (B (? Y)) ) (unificar '(f (? X) (? Y)) '(f A B)))
  (format t "        (unificar '(f A B) '(f (? X) (? Y))) -> ")
  (assert-equal '( (A (? X)) (B (? Y)) ) (unificar '(f A B) '(f (? X) (? Y))))
  (format t "        (unificar '(f (? X) C) '(f A B)) -> ")
  (assert-equal 'FALLO (unificar '(f (? X) C) '(f A B)))
  (format t "        (unificar '(f A B) '(f (? X) C)) -> ")
  (assert-equal 'FALLO (unificar '(f A B) '(f (? X) C)))
  (format t "        (unificar '(f (? X) (? Y) (? Z)) '(f A B C)) -> ")
  (assert-equal '( (A (? X)) (B (? Y)) (C (? Z)) ) (unificar '(f (? X) (? Y) (? Z)) '(f A B C)))
  (format t "        (unificar '(f A B C) '(f (? X) (? Y) (? Z))) -> ")
  (assert-equal '( (A (? X)) (B (? Y)) (C (? Z)) ) (unificar '(f A B C) '(f (? X) (? Y) (? Z))))
  (format t "        (unificar '(f (? X) (? Y) D) '(f A B C)) -> ")
  (assert-equal 'FALLO (unificar '(f (? X) (? Y) D) '(f A B C)))
  (format t "        (unificar '(f A B C) '(f (? X) (? Y) D)) -> ")
  (assert-equal 'FALLO (unificar '(f A B C) '(f (? X) (? Y) D)))
  (format t "        (unificar '(f (? X) (g (? Y))) '(f A (g B))) -> ")
  (assert-equal '( (A (? X)) (B (? Y)) ) (unificar '(f (? X) (g (? Y))) '(f A (g B))))
  (format t "        (unificar '(f A (g B)) '(f (? X) (g (? Y)))) -> ")
  (assert-equal '( (A (? X)) (B (? Y)) ) (unificar '(f A (g B)) '(f (? X) (g (? Y)))))
  (format t "        (unificar '(f (? X) (g C)) '(f A (g B))) -> ")
  (assert-equal 'FALLO (unificar '(f (? X) (g C)) '(f A (g B))))
  (format t "        (unificar '(f A (g B)) '(f (? X) (g C))) -> ")
  (assert-equal 'FALLO (unificar '(f A (g B)) '(f (? X) (g C))))
  (format t "    Pruebas de la parte de recursividad --> Tras la implementación de aplicar~%")
  (format t "        (unificar '(f (? X) (g (? X))) '(f A (g A))) -> ")
  (assert-equal '( (A (? X)) ) (unificar '(f (? X) (g (? X))) '(f A (g A))))
  (format t "        (unificar '(f A (g A)) '(f (? X) (g (? X)))) -> ")
  (assert-equal '( (A (? X)) ) (unificar '(f A (g A)) '(f (? X) (g (? X)))))
  (format t "        (unificar '(f (? X) (g (? X))) '(f A (g B))) -> ")
  (assert-equal 'FALLO (unificar '(f (? X) (g (? X))) '(f A (g B))))
  (format t "        (unificar '(f A (g B)) '(f (? X) (g (? X)))) -> ")
  (assert-equal 'FALLO (unificar '(f A (g B)) '(f (? X) (g (? X)))))
  (format t "        (unificar '(f (? X) (? Y) (g (h (? Z))) (m (g (? X)))) '(f A B (g (h C)) (m (g A)))) -> ")
  (assert-equal '( (A (? X)) (B (? Y)) (C (? Z)) ) (unificar '(f (? X) (? Y) (g (h (? Z))) (m (g (? X)))) '(f A B (g (h C)) (m (g A)))))
  (format t "        (unificar '(f A B (g (h C)) (m (g A))) '(f (? X) (? Y) (g (h (? Z))) (m (g (? X))))) -> ")
  (assert-equal '( (A (? X)) (B (? Y)) (C (? Z)) ) (unificar '(f A B (g (h C)) (m (g A))) '(f (? X) (? Y) (g (h (? Z))) (m (g (? X))))))
  (format t "        (unificar '(f (? X) B (g (h C)) (m (g (? X)))) '(f A (? Y) (g (h (? Z))) (m (g A)))) -> ")
  (assert-equal '( (A (? X)) (B (? Y)) (C (? Z)) ) (unificar '(f (? X) B (g (h C)) (m (g (? X)))) '(f A (? Y) (g (h (? Z))) (m (g A)))))
  (format t "        (unificar '(f (? X) (? Y) (g (h (? Z))) (m (g B))) '(f A B (g (h C)) (m (g A)))) -> ")
  (assert-equal 'FALLO (unificar '(f (? X) (? Y) (g (h (? Z))) (m (g B))) '(f A B (g (h C)) (m (g A)))))
  (format t "        (unificar '(f A B (g (h C)) (m (g A))) '(f (? X) (? Y) (g (h (? Z))) (m (g B)))) -> ")
  (assert-equal 'FALLO (unificar '(f A B (g (h C)) (m (g A))) '(f (? X) (? Y) (g (h (? Z))) (m (g B)))))
  (format t "        (unificar '(f (? X) B (g (h C)) (m (g B))) '(f A (? Y) (g (h (? Z))) (m (g A)))) -> ")
  (assert-equal 'FALLO (unificar '(f (? X) B (g (h C)) (m (g B))) '(f A (? Y) (g (h (? Z))) (m (g A)))))
  (format t "    Pruebas de la parte de recursividad --> Tras la implementación de componer~%")
  (format t "        (unificar '(f (? X) (? Y)) '(f (? Y) B)) -> ")
  (assert-equal '( (B (? X)) (B (? Y)) ) (unificar '(f (? X) (? Y)) '(f (? Y) B)))
  (format t "        (unificar '(f (? X) (? Y) (g (? X))) '(f (? Y) B (g B))) -> ")
  (assert-equal '( (B (? X)) (B (? Y)) ) (unificar '(f (? X) (? Y) (g (? X))) '(f (? Y) B (g B))))
  (format t "        (unificar '(f (? X) (? Z) (? Y)) '(f (? Y) C B)) -> ")
  (assert-equal '( (B (? X)) (C (? Z)) (B (? Y)) ) (unificar '(f (? X) (? Z) (? Y)) '(f (? Y) C B)))
  (format t "        (unificar '(f (? X) (? Z) (? Y) (g (? X))) '(f (? Y) C B (g (? Y)))) -> ")
  (assert-equal '( (B (? X)) (C (? Z)) (B (? Y)) ) (unificar '(f (? X) (? Z) (? Y) (g (? X))) '(f (? Y) C B (g (? Y)))))
  (format t "        (unificar '(f (? X) (? Z) (? Y) (g (? Y))) '(f (? Y) C B (g (? X)))) -> ")
  (assert-equal '( (B (? X)) (C (? Z)) (B (? Y)) ) (unificar '(f (? X) (? Z) (? Y) (g (? Y))) '(f (? Y) C B (g (? X)))))
  (format t "        (unificar '(f (? X) (? Z) (? Y) (g (? X))) '(f (? Y) C B (g C))) -> ")
  (assert-equal 'FALLO (unificar '(f (? X) (? Z) (? Y) (g (? X))) '(f (? Y) C B (g C))))
)
